# Generated by Django 3.1 on 2020-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_logo_image', models.ImageField(upload_to='service/service_logo_image')),
                ('service_heading', models.CharField(max_length=255)),
                ('service_short_description', models.TextField(max_length=500)),
            ],
        ),
    ]
