# Generated by Django 3.1 on 2020-08-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20200829_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_discription',
        ),
        migrations.AddField(
            model_name='about',
            name='about_description',
            field=models.TextField(default='Write here an about descriptions', max_length=255),
        ),
        migrations.AlterField(
            model_name='coolfact',
            name='fact_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='staff',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
