# Generated by Django 3.1 on 2020-08-29 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20200829_0711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='About',
            new_name='aboutDescription',
        ),
    ]
