# Generated by Django 3.1 on 2020-08-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_auto_20200829_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutdescription',
            name='about_thumbnail',
            field=models.ImageField(default=1, upload_to='about/about_thumbnail'),
            preserve_default=False,
        ),
    ]
