# Generated by Django 3.1 on 2020-08-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_aboutdescription_about_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolfact',
            name='fact_icon',
            field=models.CharField(choices=[('Heart', 'icon_heart_alt'), ('Genius', 'icon_genius'), ('Book', 'icon_book_alt'), ('Icon Id', 'icon_id')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
