# Generated by Django 3.1 on 2020-08-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_coolfact_fact_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coolfact',
            name='fact_icon',
            field=models.CharField(choices=[('icon_heart_alt', 'Heart'), ('icon_genius', 'Genius'), ('icon_book_alt', 'Book'), ('icon_id', 'Icon Id')], max_length=20),
        ),
    ]
